language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '10'
  - '11'
after_success:
  - yarn run semantic-release
scripts:
  - yarn install --ignore-engines
  - yarn run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
